"use client";

import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { IconSparkles, IconBarbell, IconMoon } from "@tabler/icons-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { GenerateWorkoutPlan } from "@/action/workout-plan.action";

type PlanExercise = {
  id: string;
  sets: number;
  reps: string;
  restSeconds: number;
  notes: string | null;
  exercise: {
    id: string;
    name: string;
    equipment: string | null;
    primaryMuscle: string[];
  };
};

type PlanDay = {
  id: string;
  weekNumber: number;
  dayNumber: number;
  focus: string;
  isRestDay: boolean;
  exercises: PlanExercise[];
};

export type PlanForView = {
  id: string;
  title: string;
  goal: string;
  durationWeeks: number;
  daysPerWeek: number;
  aiRationale: string | null;
  modelUsed: string | null;
  createdAt: Date;
  days: PlanDay[];
};

export function GenerateButton({ label }: { label: string }) {
  const router = useRouter();
  const [state, formAction, pending] = useActionState(GenerateWorkoutPlan, null);

  useEffect(() => {
    if (state?.success) {
      toast.success("Your plan is ready");
      router.refresh();
    } else if (state && !state.success) {
      toast.error(state.error);
    }
  }, [state, router]);

  return (
    <form action={formAction}>
      <input type="hidden" name="durationWeeks" value="4" />
      <Button type="submit" disabled={pending}>
        <IconSparkles className="mr-2 size-4" />
        {pending ? "Generating your plan…" : label}
      </Button>
      {pending && (
        <p className="text-muted-foreground mt-2 text-sm">
          This usually takes 15–30 seconds.
        </p>
      )}
    </form>
  );
}

export function WorkoutPlanView({ plan }: { plan: PlanForView }) {
  const weeks = [...new Set(plan.days.map((d) => d.weekNumber))].sort((a, b) => a - b);
  const [week, setWeek] = useState(String(weeks[0] ?? 1));

  return (
    <div className="flex flex-col gap-4">
      <Card>
        <CardHeader>
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <CardTitle className="text-2xl">{plan.title}</CardTitle>
              <CardDescription>
                {plan.durationWeeks} weeks · {plan.daysPerWeek} days per week ·{" "}
                {plan.goal.replace(/_/g, " ").toLowerCase()}
              </CardDescription>
            </div>
            <GenerateButton label="Regenerate" />
          </div>
        </CardHeader>
        {plan.aiRationale && (
          <CardContent>
            <h3 className="mb-2 text-sm font-medium">Why this plan</h3>
            <div className="text-muted-foreground space-y-2 text-sm">
              {plan.aiRationale.split("\n\n").map((para, i) => (
                <p key={i}>{para}</p>
              ))}
            </div>
            {plan.modelUsed && (
              <p className="text-muted-foreground mt-3 text-xs">
                Generated by {plan.modelUsed} on{" "}
                {new Date(plan.createdAt).toLocaleDateString()}
              </p>
            )}
          </CardContent>
        )}
      </Card>

      <Tabs value={week} onValueChange={setWeek}>
        <TabsList className="w-full">
          {weeks.map((w) => (
            <TabsTrigger key={w} value={String(w)} className="flex-1">
              Week {w}
            </TabsTrigger>
          ))}
        </TabsList>

        {weeks.map((w) => (
          <TabsContent key={w} value={String(w)} className="mt-4 flex flex-col gap-3">
            {plan.days
              .filter((d) => d.weekNumber === w)
              .sort((a, b) => a.dayNumber - b.dayNumber)
              .map((day) => (
                <Card key={day.id}>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-base">
                      {day.isRestDay ? (
                        <IconMoon className="size-4 text-muted-foreground" />
                      ) : (
                        <IconBarbell className="size-4 text-muted-foreground" />
                      )}
                      Day {day.dayNumber} — {day.focus}
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    {day.isRestDay ? (
                      <p className="text-muted-foreground text-sm">
                        Rest day. Recovery is part of the programme.
                      </p>
                    ) : (
                      <ol className="flex flex-col gap-3">
                        {day.exercises.map((ex, i) => (
                          <li key={ex.id} className="flex gap-3">
                            <span className="text-muted-foreground w-5 shrink-0 text-sm tabular-nums">
                              {i + 1}.
                            </span>
                            <div className="flex-1">
                              <div className="font-medium">{ex.exercise.name}</div>
                              <div className="text-muted-foreground text-sm">
                                {ex.sets} sets × {ex.reps} reps · {ex.restSeconds}s rest
                              </div>
                              <div className="mt-1 flex flex-wrap gap-1">
                                {ex.exercise.equipment && (
                                  <Badge variant="secondary" className="capitalize">
                                    {ex.exercise.equipment}
                                  </Badge>
                                )}
                                {ex.exercise.primaryMuscle.map((m) => (
                                  <Badge key={m} variant="outline" className="capitalize">
                                    {m}
                                  </Badge>
                                ))}
                              </div>
                              {ex.notes && (
                                <p className="text-muted-foreground mt-1 text-sm italic">
                                  {ex.notes}
                                </p>
                              )}
                            </div>
                          </li>
                        ))}
                      </ol>
                    )}
                  </CardContent>
                </Card>
              ))}
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}
