import Link from "next/link";
import { format } from "date-fns";
import { IconArrowRight } from "@tabler/icons-react";
import { GetAdminDashboard } from "@/action/dashboard.action";
import { StatGrid, StatTile, pesos } from "@/components/stat-tile";
import { ColumnChart, DataTableTwin, GroupedColumns, StatusBandBar } from "@/components/dashboard-charts";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import PendingPayments from "../sales/pending-payments/PendingPayments";

export const metadata = { title: "Dashboard" };

/**
 * Administrative dashboard (guide module 9).
 *
 * A server component: one action call, no client fetching, nothing to secure in
 * the browser. The layout is a KPI row first (the numbers a manager asks for),
 * then the four trends, then the lists that need action today.
 */
export default async function DashboardPage() {
  const d = await GetAdminDashboard();

  const collectedPct = d.revenue.thisMonthBilled > 0 ? Math.round((d.revenue.thisMonthCollected / d.revenue.thisMonthBilled) * 100) : null;
  const atRisk = d.retention.byLevel.HIGH + d.retention.byLevel.CRITICAL;

  return (
    <div className="flex flex-col gap-6 px-4 lg:px-6">
      <StatGrid>
        <StatTile label="Members" value={d.members.total} hint={`${d.members.active} with an active membership · ${d.members.newThisMonth} joined this month`} />
        <StatTile
          label="Billed this month"
          value={pesos(d.revenue.thisMonthBilled)}
          hint={collectedPct === null ? "No sales started this month" : `${pesos(d.revenue.thisMonthCollected)} collected (${collectedPct}%)`}
        />
        <StatTile
          label="Outstanding balance"
          value={pesos(d.revenue.outstanding)}
          hint={d.revenue.onlinePaidThisMonth > 0 ? `${pesos(d.revenue.onlinePaidThisMonth)} paid online this month` : "Across all memberships"}
          tone={d.revenue.outstanding > 0 ? "warning" : undefined}
        />
        <StatTile
          label="Check-ins, last 7 days"
          value={d.attendance.checkins7}
          hint={`${d.attendance.uniqueMembers7} different members · ${d.attendance.avgPerDay30}/day over 30 days`}
        />
        <StatTile
          label="Members at risk"
          value={atRisk}
          hint={d.retention.lastRun ? `${d.retention.byLevel.CRITICAL} critical · scored ${format(new Date(d.retention.lastRun), "d MMM yyyy")}` : "Retention has not been scored yet"}
          tone={d.retention.byLevel.CRITICAL > 0 ? "critical" : atRisk > 0 ? "warning" : "good"}
        />
        <StatTile
          label="Engagement score"
          value={d.engagement.avgScoreLastWeek === null ? "—" : d.engagement.avgScoreLastWeek}
          hint={d.engagement.avgConsistencyLastWeek === null ? "Computed weekly by the daily job" : `Average last week · ${d.engagement.avgConsistencyLastWeek}% plan consistency`}
        />
        <StatTile label="Active workout plans" value={d.engagement.activePlans} hint={`${d.ai.aiPlans} generated by AI in total · ${d.ai.aiPlansThisMonth} this month`} />
        <StatTile label="Trainer sessions" value={d.bookings.upcoming} hint={`upcoming · ${d.bookings.thisWeek.PENDING} awaiting confirmation this week`} />
      </StatGrid>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Daily check-ins</CardTitle>
            <CardDescription>Attendance over the last 30 days.</CardDescription>
          </CardHeader>
          <CardContent>
            <ColumnChart data={d.attendance.days} seriesLabel="Check-ins" />
            <DataTableTwin caption="Daily check-ins" rows={d.attendance.days} columns={[{ key: "date", label: "Date" }, { key: "value", label: "Check-ins" }]} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Revenue</CardTitle>
            <CardDescription>Billed against collected, by the month a membership starts. Whole pesos.</CardDescription>
          </CardHeader>
          <CardContent>
            <GroupedColumns data={d.revenue.months} labels={{ a: "Billed", b: "Collected" }} currency />
            <DataTableTwin
              caption="Monthly revenue"
              rows={d.revenue.months.map((m) => ({ month: m.label, billed: pesos(m.a), collected: pesos(m.b) }))}
              columns={[{ key: "month", label: "Month" }, { key: "billed", label: "Billed" }, { key: "collected", label: "Collected" }]}
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Workouts logged per week</CardTitle>
            <CardDescription>Completed sessions across all members, last 8 complete weeks.</CardDescription>
          </CardHeader>
          <CardContent>
            <ColumnChart data={d.engagement.weeks} seriesLabel="Workouts" />
            <DataTableTwin
              caption="Workouts per week"
              rows={d.engagement.weeks.map((w) => ({ week: `w/c ${w.label}`, workouts: w.value, score: w.avgScore ?? "—" }))}
              columns={[{ key: "week", label: "Week" }, { key: "workouts", label: "Workouts" }, { key: "score", label: "Avg engagement" }]}
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Retention risk</CardTitle>
            <CardDescription>
              Every member's latest score, banded.{" "}
              <Link href="/retention" className="underline underline-offset-2">
                Open the retention dashboard
              </Link>
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            {d.retention.total === 0 ? (
              <p className="text-muted-foreground text-sm">Not scored yet — run the daily job from Notifications, or Recalculate on the retention page.</p>
            ) : (
              <StatusBandBar
                segments={[
                  { key: "LOW", label: "low risk", value: d.retention.byLevel.LOW, status: "good", hint: "No action needed" },
                  { key: "MEDIUM", label: "medium", value: d.retention.byLevel.MEDIUM, status: "warning", hint: "Keep an eye on" },
                  { key: "HIGH", label: "high", value: d.retention.byLevel.HIGH, status: "serious", hint: "Reach out this week" },
                  { key: "CRITICAL", label: "critical", value: d.retention.byLevel.CRITICAL, status: "critical", hint: "Call today" },
                ]}
              />
            )}
            <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">
              <div>
                <div className="text-xl font-semibold">{d.bookings.thisWeek.CONFIRMED + d.bookings.thisWeek.COMPLETED}</div>
                <p className="text-muted-foreground text-xs">Trainer sessions this week</p>
              </div>
              <div>
                <div className="text-xl font-semibold">{d.bookings.thisWeek.NO_SHOW}</div>
                <p className="text-muted-foreground text-xs">No-shows this week</p>
              </div>
              <div>
                <div className="text-xl font-semibold">{d.ai.assistantReplies}</div>
                <p className="text-muted-foreground text-xs">Assistant replies, all time</p>
              </div>
              <div>
                <div className="text-xl font-semibold">{d.ai.notifications7d}</div>
                <p className="text-muted-foreground text-xs">Notifications, last 7 days</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Memberships ending in the next 7 days</CardTitle>
          <CardDescription>
            These members have been (or will be) reminded automatically. Anyone with a balance is worth a call.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {d.members.expiring7.length === 0 ? (
            <p className="text-muted-foreground text-sm">Nothing expiring this week.</p>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Member</TableHead>
                    <TableHead>Service</TableHead>
                    <TableHead>Ends</TableHead>
                    <TableHead className="text-right">Balance</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {d.members.expiring7.map((m) => (
                    <TableRow key={`${m.id}-${m.endDate}`}>
                      <TableCell>
                        <span className="font-medium">{m.name}</span> <span className="text-muted-foreground">{m.memberCode}</span>
                      </TableCell>
                      <TableCell>{m.service}</TableCell>
                      <TableCell className="tabular-nums">{m.endDate}</TableCell>
                      <TableCell className={`text-right tabular-nums ${m.due > 0 ? "text-amber-700 dark:text-amber-400" : ""}`}>{pesos(m.due)}</TableCell>
                      <TableCell className="text-right">
                        <Link href={`/members/${m.id}`}>
                          <Button variant="ghost" size="sm">
                            Open <IconArrowRight className="ml-1 size-4" />
                          </Button>
                        </Link>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      <PendingPayments />
    </div>
  );
}
